name: CI
on:
  push:
    paths:
      - '.github/workflows/main.yml'
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.2
      
#     - name: Azure login
#       uses: Azure/login@v1
#       with:
#         creds: ${{secrets.AZURE_CREDENTIALS}}
      
    - name: running postgresql action
      uses: aksm-ms/postgresql-action@master
      with:
#         connection-string: 'psql host=ak-db.postgres.database.azure.com port=5432 dbname=postgres user=aksm@ak-db password=Mads.handyvs!2 sslmode=require'
        connection-string: ${{secrets.CONN_STRING}}
        server-name: "ak-db.postgres.database.azure.com"
#         plsql-file: "./sql_files/x/*.sql"
        plsql-file: "sql_files/*/*.sql"
#         plsql-file: "1.xyz"
#         arguments: '-c "SELECT 99"'
    
