name: CI

on:
  push:
    paths:
      - '.github/workflows/postgresql.yml'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [windows-latest, ubuntu-latest, macos-latest]
          max-parallel: 1
    
    steps:
    - uses: actions/checkout@v2
    
    - name: '10 lines'
      uses: aksm-ms/postgresql-action@master
      with:
        connection-string: ${{secrets.AZURE_POSTGRES_CONN_STRING}}
        server-name: "ak-db.postgres.database.azure.com"
        plsql-file: "./sql_files/postgresql-action/10-lines.sql"

    - name: '100 lines'
      uses: aksm-ms/postgresql-action@master
      with:
        connection-string: ${{secrets.AZURE_POSTGRES_CONN_STRING}}
        server-name: "ak-db.postgres.database.azure.com"
        plsql-file: "./sql_files/postgresql-action/100-lines.sql"

    - name: '1000 lines'
      uses: aksm-ms/postgresql-action@master
      with:
        connection-string: ${{secrets.AZURE_POSTGRES_CONN_STRING}}
        server-name: "ak-db.postgres.database.azure.com"
        plsql-file: "./sql_files/postgresql-action/1000-lines.sql"

    - name: '10000 lines'
      uses: aksm-ms/postgresql-action@master
      with:
        connection-string: ${{secrets.AZURE_POSTGRES_CONN_STRING}}
        server-name: "ak-db.postgres.database.azure.com"
        plsql-file: "./sql_files/postgresql-action/10000-lines.sql"